# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getRTSpectMatrix <- function(mat, rt_vect, class_vect, rt_threshold, corr_threshold) {
    .Call('_erah_getRTSpectMatrix', PACKAGE = 'erah', mat, rt_vect, class_vect, rt_threshold, corr_threshold)
}

runmean <- function(In, nWin) {
    .Call('_erah_runmean', PACKAGE = 'erah', In, nWin)
}

runmin <- function(In, nWin) {
    .Call('_erah_runmin', PACKAGE = 'erah', In, nWin)
}

